services:
  - type: web
    name: chu-dialyse-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://chu-dialyse-backend.onrender.com
